language: node_js
node_js:
  - node
os:
  - linux
  - osx
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "Running in Linux!" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get install -y libasound2-dev  ; fi
